config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'login',  to: 'static_pages#login'
  post 'login',  to: 'users#login'
  get  'logout', to: 'users#logout'

  get  'events/:id/attend', to: 'events#attend', as: 'attend_event'
  get  'events/:id/unattend', to: 'events#unattend', as: 'unattend_event'  

  resources :users, :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances

  scope :soonest, -> { order('datetime - CURRENT_TIMESTAMP ASC') }
  scope :most_recent, -> { order('CURRENT_TIMESTAMP - datetime ASC') }

  scope :upcoming, -> { where('datetime > CURRENT_TIMESTAMP').soonest }
  scope :past, -> { where('datetime < CURRENT_TIMESTAMP').most_recent }

  validates :name, :location, :datetime, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :events, foreign_key: 'creator_id'
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: %i[attend, unattend, destroy]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    if logged_in?
      @going = @event.attendees.include?(current_user) ? true : false
    end
  end

  def index
    @upcoming = Event.upcoming
    @past = Event.past
  end

  def destroy
    if !(event = Event.find_by(params[:id]))
      flash[:danger] = "Event not found."
      redirect_to events_path
    elsif !helpers.hosting?(event)
      flash[:danger] = "You can't delete an event you're not hosting."
      redirect_to event
    else
      event.destroy
      flash[:success] = "Event deleted."
      redirect_to current_user
    end
  end

  def attend
    if !(event = Event.find(params[:id]))
      flash[:danger] = "Invalid event."
      redirect_to events_path
    elsif helpers.going?(event)
      flash[:warning] = "You're already going to #{event.name}!"
      redirect_to event
    elsif helpers.hosting?(event)
      flash[:warning] = "You're already hosting #{event.name}."
      redirect_to event
    else
      event.attendees << current_user
      flash[:success] = "You're going to #{event.name}!"
      redirect_to event
    end
  end

  def unattend
    if !(event = Event.find(params[:id]))
      flash[:danger] = "Invalid event."
      redirect_to events_path
    elsif !helpers.going?(event)
      flash[:warning] = "You're already not going to #{event.name}!"
      redirect_to event
    elsif helpers.hosting?(event)
      flash[:warning] = "You're already hosting #{event.name}."
      redirect_to event
    else
      event.attendees.destroy(current_user)
      flash[:success] = "You're no longer going to #{event.name}."
      redirect_to event
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :datetime, :description)
  end

  def require_login
    unless logged_in? 
      flash[:danger] = 'You need to login to do that.'
      redirect_to login_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @upcoming_count = current_user.events.upcoming.count
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @hosted = @user.events.all
    @upcoming = @user.attended_events.upcoming
    @past = @user.attended_events.past
  end

  def login
    if (@user = User.find_by(email: params[:user][:email]))
      session[:user_id] = @user.id
      flash[:sucess] = "You are now logged in as #{current_user.name}."
      redirect_to root_url
    else
      flash.now[:danger] = 'Login unsuccessful.'
      redirect_to login_path
    end
  end

  def logout
    reset_session
    @current_user = nil
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_date(datetime)
    datetime.strftime('%A, %B %d at %I:%M %p')
  end

  def going?(event)
    if logged_in?
      event.attendees.include?(current_user) ? true : false
    else
      false
    end
  end

  def hosting?(event)
    if logged_in?
      current_user.events.include?(event) ? true : false
    else
      false
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/events/index.html.haml
- provide :title, "Events"

= render partial: 'shared/events_feed', locals: { events: @upcoming, name: 'upcoming' }
= render partial: 'shared/events_feed', locals: { events: @past, name: 'past' }

app/views/events/new.html.haml
- provide :title, "New Event"

= form_for @event do |f|
  = f.label :name
  = f.text_field :name
  = f.label :location
  = f.text_field :location
  = f.label :date
  .select
    = f.datetime_select :datetime, order: [:day, :month, :year, :hour, :minute], ampm: true, start_year: Date.current.year, end_year: Date.current.year + 10, minute_step: 10
  = f.label :description
  = f.text_area :description
  %br
  = f.submit

app/views/events/show.html.haml
- provide :title, @event.name

.event
  .date ⏰ #{format_date(@event.datetime)}
  .location 🌎 #{@event.location}
  .description 🖉 #{@event.description}
  .host 👤 Hosted by #{link_to(@event.creator.name, @event.creator)}
  .going 🎈 Going:
  - @event.attendees.each do |attendee|
    .attendee= link_to(attendee.name, attendee)
.actions
  = render 'shared/event_actions', event: @event

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title #{yield :title} | eventloop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    = render 'shared/header'
    = render 'shared/flash'
    = yield

app/views/shared/_event_actions.html.haml
- if logged_in?
  - if hosting?(event)
    .status You're hosting this event.
    .action= link_to "Delete", event_path(event.id), method: :delete
  - elsif going?(event)
    .status You're going to this event.
    .action= link_to "Not Going", unattend_event_path(event.id)
  - else
    .status You're not going to this event yet.
    .action= link_to "I'm Going", attend_event_path(event.id)

app/views/shared/_events_feed.html.haml
.kind= "#{name.capitalize} Events"
.feed
  - if events.any?
    - events.each do |event|
      .event
        = link_to(event.name, event, class: :name)
        .date ⏰ #{format_date(event.datetime)}
        .location 🌎 #{event.location}
        .description 🖉 #{event.description.truncate(50)}
        .going 🎈 #{pluralize(event.attendees.count, 'person')} going.
        - if !current_page?(controller: 'users')
          %div
            .host 👤 Hosted by #{link_to(event.creator.name, event.creator)}
      .actions
        = render 'shared/event_actions', event: event
  - else
    .event= "No #{name} events."
    %br

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  %div{class: "flash flash-#{type}"}= message
  %br

app/views/shared/_header.html.haml
- if !current_page?('/')
  %h1.title= yield :title

app/views/shared/_navbar.html.haml
%nav.navbar
  %ul
    %li= link_to 'Home', root_url
    %li= link_to 'Browse', events_path
    - if logged_in?
      %li= link_to 'Your Events', current_user
      %li= link_to 'New Event', new_event_path
      %li= link_to 'Logout', logout_path
    - else
      %li= link_to 'Login', login_path
      %li= link_to 'Sign Up', new_user_path

app/views/static_pages/home.html.haml
- provide :title, "Home"

=image_tag 'background.jpg', class: 'bg'

%h1.brand eventloop

.home
  - if logged_in?
    .greeting Hello #{current_user.name}!
    .counter You have #{link_to "#{pluralize(@upcoming_count, 'upcoming event')}!", current_user}
    .button.browse= link_to "Find more events", events_path
  - else
    .button.login= link_to "Log in", login_path
    .button.signup= link_to "Sign up", new_user_path
    .button.browse= link_to "Browse", events_path

app/views/static_pages/login.html.haml
- provide :title, "Log in"

.center (Try brxck@test.com)
%br

= form_for :user do |f|
  = f.label :email
  = f.text_field :email
  %br
  = f.submit "Log in"
  %br
.center= link_to "Create Account", new_user_path

app/views/users/new.html.haml
- provide :title, "New User"

= form_for @user do |f|
  = f.label :name
  = f.text_field :name  
  = f.label :email
  = f.email_field :email  
  = f.label :password
  = f.password_field :password  
  = f.label :password_confirmation  
  = f.password_field :password_confirmation
  %br
  = f.submit

app/views/users/show.html.haml
- provide :title, @user.name

= render partial: 'shared/events_feed', locals: {events: @hosted, name: 'hosted'}
= render partial: 'shared/events_feed', locals: {events: @upcoming, name: 'upcoming'}
= render partial: 'shared/events_feed', locals: {events: @past, name: 'past'}